name: Python CI

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Check Python versions ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run unit tests
      run: |
        python -m unittest discover

    - name: Lint with ruff
      run: |
        ruff check .

    - name: Check formatting with black
      run: |
        black . --check