name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pygame numpy cupy-cuda13x
    - name: Lint with flake8
      run: |
        # F401: Ignores "module imported but unused" errors for cupy
        # E501: Ignores "line too long" errors
        flake8 . --count --show-source --statistics --ignore=F401,E501